FROM centos:7
MAINTAINER Gopala Krishnan <gopac25@gmail.com>
RUN yum -y install which git wget unzip python-devel epel-release initscripts vim && \
    yum -y groupinstall 'Development Tools' && \
    yum -y install java-1.8.0-openjdk-devel  && \
    curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | tee /etc/yum.repos.d/jenkins.repo && \
    rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key && \
    yum -y install jenkins && \
    yum -y install ansible && \
    yum -y install python-pip && \
    wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip && \
    unzip ./terraform_0.11.13_linux_amd64.zip -d /usr/local/bin/ && \
    yum -y upgrade python* && \
    chown -c jenkins /var/lib/jenkins && \
    chsh -s /bin/bash jenkins
CMD "/usr/sbin/init" && \
    "systemctl start jenkins" && \
    "systemctl enable jenkins"
ENTRYPOINT /usr/sbin/init
